#!/usr/bin/env bash
# Source this file before running the drop6 binary classifier in WSL/Linux.
#
# Usage:
#   source ./set_blackbox_drop6_wsl_env.sh
#   bash blackbox_finetune_drop6/scripts/one_click_deploy.sh full

set -euo pipefail

SAMPLE_MODE="${1:-${SAMPLE_MODE:-xlong}}"
BLACKBOX_DROP_DIR="${BLACKBOX_DROP_DIR:-blackbox_finetune_drop6}"
MODEL_TAG="${MODEL_TAG:-drop6}"

case "$SAMPLE_MODE" in
  short)
    DEFAULT_MAX_SEQ_LENGTH=1024
    ;;
  long)
    DEFAULT_MAX_SEQ_LENGTH=2048
    ;;
  xlong)
    DEFAULT_MAX_SEQ_LENGTH=3072
    ;;
  xxlong)
    DEFAULT_MAX_SEQ_LENGTH=4096
    ;;
  *)
    echo "Unsupported SAMPLE_MODE: $SAMPLE_MODE" >&2
    return 2 2>/dev/null || exit 2
    ;;
esac

export BLACKBOX_DROP_DIR
export MODEL_LABEL_VALUE="$MODEL_TAG"
export MODEL_TAG
export SAMPLE_MODE
export PYTHON_BIN="${PYTHON_BIN:-python3}"
export VENV_DIR="${VENV_DIR:-$HOME/.venvs/astock-blackbox-finetune-${MODEL_TAG}}"
export BASE_MODEL="${BASE_MODEL:-Qwen/Qwen2.5-0.5B-Instruct}"
export HF_LOCAL_FILES_ONLY="${HF_LOCAL_FILES_ONLY:-1}"
export HF_HUB_OFFLINE="${HF_HUB_OFFLINE:-1}"
export TRANSFORMERS_OFFLINE="${TRANSFORMERS_OFFLINE:-1}"
export TRUST_REMOTE_CODE="${TRUST_REMOTE_CODE:-0}"
export CUDA_DEVICE="${CUDA_DEVICE:-0}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-$CUDA_DEVICE}"
export USE_4BIT="${USE_4BIT:-1}"
export ON_THE_FLY_TOKENIZE="${ON_THE_FLY_TOKENIZE:-1}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export RESUME_ADAPTER_DIR="${RESUME_ADAPTER_DIR:-}"
export INITIAL_ADAPTER_DIR="${INITIAL_ADAPTER_DIR:-}"
if [[ -n "$INITIAL_ADAPTER_DIR" && "$INITIAL_ADAPTER_DIR" == *\\* ]] && command -v wslpath >/dev/null 2>&1; then
  export INITIAL_ADAPTER_DIR="$(wslpath -u "$INITIAL_ADAPTER_DIR")"
fi

export TRAIN_START_DATE="${TRAIN_START_DATE:-20230101}"
export TRAIN_END_DATE="${TRAIN_END_DATE:-20241231}"
export VALIDATION_START_DATE="${VALIDATION_START_DATE:-20260101}"
export VALIDATION_END_DATE="${VALIDATION_END_DATE:-20260530}"
export TRAIN_DATASET_PATH="${TRAIN_DATASET_PATH:-}"
export TEST_DATASET_PATH="${TEST_DATASET_PATH:-}"
export VALIDATION_DATASET_PATH="${VALIDATION_DATASET_PATH:-}"
export EXPLICIT_DATASET_WORK_DIR="${EXPLICIT_DATASET_WORK_DIR:-}"

export MAX_SEQ_LENGTH="${MAX_SEQ_LENGTH_OVERRIDE:-$DEFAULT_MAX_SEQ_LENGTH}"
export EPOCHS="${EPOCHS_OVERRIDE:-0.3}"
export GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-16}"
export RANDOM_SEED="${RANDOM_SEED:-937498347}"
export TRAIN_SEED="${TRAIN_SEED:-$RANDOM_SEED}"
export EVAL_RANDOM_SEED="${EVAL_RANDOM_SEED:-20260530}"
export LEARNING_RATE="${LEARNING_RATE:-5e-6}"
export WEIGHT_DECAY="${WEIGHT_DECAY:-0.02}"
export MAX_GRAD_NORM="${MAX_GRAD_NORM:-1.0}"
export LORA_RANK="${LORA_RANK:-8}"
export LORA_DROPOUT="${LORA_DROPOUT:-0.2}"
export NEGATIVE_RATIO="${NEGATIVE_RATIO_OVERRIDE:-9.0}"
export SAMPLE_BOTTOM_BAND_RATIO="${SAMPLE_BOTTOM_BAND_RATIO:-1.0}"

export CHECKPOINT_EVERY="${CHECKPOINT_EVERY:-100}"
export EVAL_THRESHOLD="${EVAL_THRESHOLD_OVERRIDE:-0.48}"
export PRECISION_TOP_K="${PRECISION_TOP_K:-10}"
export PRECISION_THRESHOLD="${PRECISION_THRESHOLD:-${MIN_PRECISION_AT_20:-${PRECISION_AT_20_TARGET:-0.4}}}"
export MIN_PRECISION_AT_20="$PRECISION_THRESHOLD"
export EVAL_PRECISION_TOP_K="${EVAL_PRECISION_TOP_K:-$PRECISION_TOP_K}"
export EVAL_PRECISION_THRESHOLD="${EVAL_PRECISION_THRESHOLD:-${EVAL_MIN_PRECISION_AT_20:-$PRECISION_THRESHOLD}}"
export EVAL_SAMPLE_METHOD="${EVAL_SAMPLE_METHOD:-random}"
export EVAL_MAX_SAMPLES="${EVAL_MAX_SAMPLES:-1000}"

export OOM_PATIENCE="${OOM_PATIENCE:-20}"
export NONFINITE_SKIP_LIMIT="${NONFINITE_SKIP_LIMIT:-100}"
export NONFINITE_BACKOFF_EVERY="${NONFINITE_BACKOFF_EVERY:-10}"
export LR_BACKOFF_FACTOR="${LR_BACKOFF_FACTOR:-0.5}"
export MIN_LEARNING_RATE="${MIN_LEARNING_RATE:-1e-6}"

printf '%s\n' \
  "Loaded WSL/Linux drop6 blackbox defaults:" \
  "  [project]" \
  "  BLACKBOX_DROP_DIR=$BLACKBOX_DROP_DIR" \
  "  MODEL_TAG=$MODEL_TAG" \
  "  SAMPLE_MODE=$SAMPLE_MODE" \
  "  LABEL_RULE=positive if next 3 trading days low <= anchor close * 0.94" \
  "  NEGATIVE_RULE=exclude samples within +/-10 trading days of any same-stock positive" \
  "  TRAINING_LOSS=causal_lm_cross_entropy" \
  "  [model/runtime]" \
  "  BASE_MODEL=$BASE_MODEL" \
  "  VENV_DIR=$VENV_DIR" \
  "  PYTHON_BIN=$PYTHON_BIN" \
  "  CUDA_DEVICE=$CUDA_DEVICE" \
  "  CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES" \
  "  USE_4BIT=$USE_4BIT" \
  "  ON_THE_FLY_TOKENIZE=$ON_THE_FLY_TOKENIZE" \
  "  HF_LOCAL_FILES_ONLY=$HF_LOCAL_FILES_ONLY" \
  "  HF_HUB_OFFLINE=$HF_HUB_OFFLINE" \
  "  TRANSFORMERS_OFFLINE=$TRANSFORMERS_OFFLINE" \
  "  TRUST_REMOTE_CODE=$TRUST_REMOTE_CODE" \
  "  RESUME_ADAPTER_DIR=${RESUME_ADAPTER_DIR:-<unset>}" \
  "  INITIAL_ADAPTER_DIR=${INITIAL_ADAPTER_DIR:-<unset>}" \
  "  [data]" \
  "  TRAIN_START_DATE=$TRAIN_START_DATE" \
  "  TRAIN_END_DATE=$TRAIN_END_DATE" \
  "  VALIDATION_START_DATE=$VALIDATION_START_DATE" \
  "  VALIDATION_END_DATE=$VALIDATION_END_DATE" \
  "  NEGATIVE_RATIO=$NEGATIVE_RATIO" \
  "  NEGATIVE_RATIO_OVERRIDE=${NEGATIVE_RATIO_OVERRIDE:-<unset>}" \
  "  SAMPLE_BOTTOM_BAND_RATIO=$SAMPLE_BOTTOM_BAND_RATIO" \
  "  REBUILD_DATASET=${REBUILD_DATASET:-<unset>}" \
  "  REBUILD_VALIDATION_DATASET=${REBUILD_VALIDATION_DATASET:-<unset>}" \
  "  [training]" \
  "  MAX_SEQ_LENGTH=$MAX_SEQ_LENGTH" \
  "  MAX_SEQ_LENGTH_OVERRIDE=${MAX_SEQ_LENGTH_OVERRIDE:-<unset>}" \
  "  EPOCHS=$EPOCHS" \
  "  EPOCHS_OVERRIDE=${EPOCHS_OVERRIDE:-<unset>}" \
  "  GRADIENT_ACCUMULATION_STEPS=$GRADIENT_ACCUMULATION_STEPS" \
  "  RANDOM_SEED=$RANDOM_SEED" \
  "  TRAIN_SEED=$TRAIN_SEED" \
  "  LEARNING_RATE=$LEARNING_RATE" \
  "  WEIGHT_DECAY=$WEIGHT_DECAY" \
  "  MAX_GRAD_NORM=$MAX_GRAD_NORM" \
  "  LORA_RANK=$LORA_RANK" \
  "  LORA_DROPOUT=$LORA_DROPOUT" \
  "  CHECKPOINT_EVERY=$CHECKPOINT_EVERY" \
  "  NO_AUTO_RESUME=${NO_AUTO_RESUME:-<unset>}" \
  "  [evaluation]" \
  "  EVALUATION_GATE=precision@$PRECISION_TOP_K >= $PRECISION_THRESHOLD" \
  "  PRECISION_TOP_K=$PRECISION_TOP_K" \
  "  PRECISION_THRESHOLD=$PRECISION_THRESHOLD" \
  "  EVAL_PRECISION_TOP_K=$EVAL_PRECISION_TOP_K" \
  "  EVAL_PRECISION_THRESHOLD=$EVAL_PRECISION_THRESHOLD" \
  "  EVAL_THRESHOLD=$EVAL_THRESHOLD" \
  "  EVAL_RANDOM_SEED=$EVAL_RANDOM_SEED" \
  "  EVAL_SAMPLE_METHOD=$EVAL_SAMPLE_METHOD" \
  "  EVAL_MAX_SAMPLES=$EVAL_MAX_SAMPLES" \
  "  RUN_FINAL_EVAL=${RUN_FINAL_EVAL:-<unset>}" \
  "  [stability]" \
  "  OOM_PATIENCE=$OOM_PATIENCE" \
  "  NONFINITE_SKIP_LIMIT=$NONFINITE_SKIP_LIMIT" \
  "  NONFINITE_BACKOFF_EVERY=$NONFINITE_BACKOFF_EVERY" \
  "  LR_BACKOFF_FACTOR=$LR_BACKOFF_FACTOR" \
  "  MIN_LEARNING_RATE=$MIN_LEARNING_RATE" \
  "" \
  "Run:" \
  "  bash $BLACKBOX_DROP_DIR/scripts/one_click_deploy.sh full"
