#!/usr/bin/env bash

export BASE_MODEL="${BASE_MODEL:-Qwen/Qwen2.5-0.5B-Instruct}"
export VENV_DIR="${VENV_DIR:-$HOME/.venvs/astock-blackbox-threeclass}"
export SAMPLE_MODE="${SAMPLE_MODE:-xlong}"
export MAX_SEQ_LENGTH="${MAX_SEQ_LENGTH:-3072}"
export TRAIN_START_DATE="${TRAIN_START_DATE:-20230101}"
export TRAIN_END_DATE="${TRAIN_END_DATE:-20241231}"
export VALIDATION_START_DATE="${VALIDATION_START_DATE:-20260101}"
export VALIDATION_END_DATE="${VALIDATION_END_DATE:-20260530}"
export DATA_DIR="${DATA_DIR:-blackbox_finetune_threeclass/data_xlong_p1_n4_u10}"
export VALIDATION_DATA_DIR="${VALIDATION_DATA_DIR:-blackbox_finetune_threeclass/data_evaluation_xlong_p1_n4_u10}"
export OUTPUT_DIR="${OUTPUT_DIR:-blackbox_finetune_threeclass/runs/qwen2.5-0.5b-threeclass-xlong-p1_n4_u10-lora}"
export INITIAL_BINARY_ADAPTER_DIR="${INITIAL_BINARY_ADAPTER_DIR:-}"
export EPOCHS="${EPOCHS:-1.0}"
export BATCH_SIZE="${BATCH_SIZE:-1}"
export GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-32}"
export LEARNING_RATE="${LEARNING_RATE:-5e-6}"
export WEIGHT_DECAY="${WEIGHT_DECAY:-0.05}"
export MAX_GRAD_NORM="${MAX_GRAD_NORM:-1.0}"
export LORA_RANK="${LORA_RANK:-8}"
export LORA_DROPOUT="${LORA_DROPOUT:-0.3}"
export POSITIVE_CE_WEIGHT="${POSITIVE_CE_WEIGHT:-2.0}"
export NEGATIVE_CE_WEIGHT="${NEGATIVE_CE_WEIGHT:-1.0}"
export NEUTRAL_CE_WEIGHT="${NEUTRAL_CE_WEIGHT:-0.5}"
export FP_LOSS_WEIGHT="${FP_LOSS_WEIGHT:-1.0}"
export RANK_LOSS_WEIGHT="${RANK_LOSS_WEIGHT:-0.5}"
export RANK_MARGIN="${RANK_MARGIN:-0.2}"
export POSITIVE_HIGH_SCORE_LOSS_WEIGHT="${POSITIVE_HIGH_SCORE_LOSS_WEIGHT:-1.0}"
export POSITIVE_HIGH_SCORE_MARGIN="${POSITIVE_HIGH_SCORE_MARGIN:-0.0}"
export HIGH_SCORE_EMA="${HIGH_SCORE_EMA:-1}"
export HIGH_SCORE_EMA_ALPHA="${HIGH_SCORE_EMA_ALPHA:-0.02}"
export HIGH_SCORE_CUTOFF_POSITION="${HIGH_SCORE_CUTOFF_POSITION:-0.6}"
export HIGH_SCORE_POSITIVE_BONUS="${HIGH_SCORE_POSITIVE_BONUS:-1.0}"
export HIGH_SCORE_NEGATIVE_PENALTY_WEIGHT="${HIGH_SCORE_NEGATIVE_PENALTY_WEIGHT:-1.0}"
export FP_DYNAMIC_PENALTY="${FP_DYNAMIC_PENALTY:-1}"
export FP_THRESHOLD_EMA_ALPHA="${FP_THRESHOLD_EMA_ALPHA:-0.02}"
export CHECKPOINT_EVERY="${CHECKPOINT_EVERY:-100}"
export TRAIN_SEED="${TRAIN_SEED:-937498347}"
export EVAL_RANDOM_SEED="${EVAL_RANDOM_SEED:-20260530}"
export EVAL_SAMPLE_METHOD="${EVAL_SAMPLE_METHOD:-random}"
export EVAL_MAX_SAMPLES="${EVAL_MAX_SAMPLES:-1500}"
export EVAL_PRECISION_TOP_K="${EVAL_PRECISION_TOP_K:-10}"
export EVAL_PRECISION_THRESHOLD="${EVAL_PRECISION_THRESHOLD:-0.40}"
export NEGATIVE_WEIGHT="${NEGATIVE_WEIGHT:-0.5}"
export NEUTRAL_WEIGHT="${NEUTRAL_WEIGHT:-0.0}"
export EVAL_THRESHOLD_TOP_RATIO="${EVAL_THRESHOLD_TOP_RATIO:-0.2}"
export SAMPLE_BOTTOM_BAND_RATIO="${SAMPLE_BOTTOM_BAND_RATIO:-1.0}"
export ON_THE_FLY_TOKENIZE="${ON_THE_FLY_TOKENIZE:-1}"
export CUDA_DEVICE="${CUDA_DEVICE:-0}"
export HF_LOCAL_FILES_ONLY="${HF_LOCAL_FILES_ONLY:-1}"
export HF_HUB_OFFLINE="${HF_HUB_OFFLINE:-1}"
export TRANSFORMERS_OFFLINE="${TRANSFORMERS_OFFLINE:-1}"
export TRUST_REMOTE_CODE="${TRUST_REMOTE_CODE:-0}"
export REBUILD_DATASET="${REBUILD_DATASET:-0}"
export CANDIDATE_BATCH_SIZE="${CANDIDATE_BATCH_SIZE:-80}"
export MYSQL_QUERY_RETRIES="${MYSQL_QUERY_RETRIES:-3}"

printf '%s\n' "Loaded three-class WSL/Linux defaults:"
for name in \
  BASE_MODEL VENV_DIR SAMPLE_MODE MAX_SEQ_LENGTH \
  TRAIN_START_DATE TRAIN_END_DATE VALIDATION_START_DATE VALIDATION_END_DATE \
  DATA_DIR VALIDATION_DATA_DIR OUTPUT_DIR INITIAL_BINARY_ADAPTER_DIR EPOCHS BATCH_SIZE \
  GRADIENT_ACCUMULATION_STEPS LEARNING_RATE WEIGHT_DECAY MAX_GRAD_NORM \
  LORA_RANK LORA_DROPOUT POSITIVE_CE_WEIGHT NEGATIVE_CE_WEIGHT NEUTRAL_CE_WEIGHT FP_LOSS_WEIGHT \
  RANK_LOSS_WEIGHT RANK_MARGIN POSITIVE_HIGH_SCORE_LOSS_WEIGHT POSITIVE_HIGH_SCORE_MARGIN \
  HIGH_SCORE_EMA HIGH_SCORE_EMA_ALPHA \
  HIGH_SCORE_CUTOFF_POSITION HIGH_SCORE_POSITIVE_BONUS HIGH_SCORE_NEGATIVE_PENALTY_WEIGHT \
  FP_DYNAMIC_PENALTY FP_THRESHOLD_EMA_ALPHA CHECKPOINT_EVERY TRAIN_SEED EVAL_RANDOM_SEED \
  EVAL_SAMPLE_METHOD EVAL_MAX_SAMPLES EVAL_PRECISION_TOP_K \
  EVAL_PRECISION_THRESHOLD NEGATIVE_WEIGHT NEUTRAL_WEIGHT EVAL_THRESHOLD_TOP_RATIO \
  SAMPLE_BOTTOM_BAND_RATIO ON_THE_FLY_TOKENIZE CUDA_DEVICE \
  HF_LOCAL_FILES_ONLY HF_HUB_OFFLINE TRANSFORMERS_OFFLINE TRUST_REMOTE_CODE \
  REBUILD_DATASET CANDIDATE_BATCH_SIZE MYSQL_QUERY_RETRIES; do
  printf '  %s=%s\n' "$name" "${!name}"
done
